---
# General system settings
timezone: Europe/Berlin
keyboard:
  layout: de
locale: de_DE.UTF-8
apt:
  sources:
    php:
      source: ppa:ondrej/php
      keyid: B8DC7E53946656EFBCE4C1DD71DAEAAB4AD4CAB6
package_update: true
package_upgrade: true

# Install required packages
packages:
  - apache2
  - curl
  - git
  - imagemagick
  - libapache2-mod-php8.3
  - mariadb-client
  - mariadb-server
  - mc
  - php8.3
  - php8.3-apcu
  - php8.3-cli
  - php8.3-common
  - php8.3-curl
  - php8.3-gd
  - php8.3-imagick
  - php8.3-intl
  - php8.3-mbstring
  - php8.3-mysql
  - php8.3-opcache
  - php8.3-redis
  - php8.3-uploadprogress
  - php8.3-xml
  - php8.3-zip
  - redis
  - wget

# Add some configuration files
write_files:
  - path: /etc/mysql/conf.d/mysql.cnf
    owner: root:root
    permissions: '0644'
    defer: true
    content: |
      [mysqld]
      innodb_buffer_pool_size=256M
      innodb_flush_log_at_trx_commit=2
      max_allowed_packet=64M

  - path: /etc/apache2/sites-available/drupal.conf
    owner: root:root
    permissions: '0644'
    defer: true
    content: |
      <VirtualHost *:80>
          ServerName localhost
          ServerAlias *
          ServerAdmin webmaster@localhost
          DocumentRoot /var/www/html/web

          <Directory /var/www/html/web>
              Options FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>

          ErrorLog ${APACHE_LOG_DIR}/error.log
          CustomLog ${APACHE_LOG_DIR}/access.log combined
      </VirtualHost>

  - path: /home/ubuntu/.bash_aliases
    owner: ubuntu:ubuntu
    permissions: '0644'
    defer: true
    content: |
      alias drush="/var/www/html/vendor/bin/drush"

  - path: /etc/php/8.3/apache2/conf.d/99-custom.ini
    owner: root:root
    permissions: '0644'
    defer: true
    content: |
      max_input_vars = 4000
      memory_limit = 512M
      post_max_size = 64M
      upload_max_filesize = 64M
      opcache.memory_consumption = 256

# Additional configuration steps
runcmd:

  # Set the root password for MariaDB and create the Drupal user and database
  - mysqladmin -u root -h localhost password "root"
  - mysql -u root -proot -e "CREATE DATABASE drupal;"
  - mysql -u root -proot -e "CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal';"
  - mysql -u root -proot -e "GRANT ALL PRIVILEGES ON drupal.* TO 'drupal'@'localhost';"
  - mysql -u root -proot -e "FLUSH PRIVILEGES;"

  # Install Composer
  - wget -O /usr/local/bin/composer https://getcomposer.org/download/latest-stable/composer.phar
  - chmod +x /usr/local/bin/composer

  # Enable Apache modules
  - a2enmod rewrite
  - a2enmod headers

  # Enable Apache site configuration
  - a2ensite drupal
  - a2dissite 000-default

  # Restart services
  - service apache2 restart
  - service mariadb restart

  # Prepare the web directory
  - usermod -a -G www-data ubuntu
  - chown -R ubuntu:ubuntu /var/www/html
  - rm /var/www/html/index.html
